name: Deploy site folder to hosting

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload /site via SFTP (password)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}   # 22 on Xneelo; try 2222 only if 22 fails
          source: site/**
          target: ${{ secrets.TARGET_DIR }}
          overwrite: true
          strip_components: 1
