name: Deploy WHMCS Timekeeper (DEV)

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/addons/timekeeper/**'
      - '.github/workflows/deploy-whmcs-timekeeper.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-whmcs-timekeeper-dev
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sanity: secrets set + local folder exists
      - name: Sanity check
        run: |
          set -e
          [ -n "${{ secrets.SSH_HOST }}" ] && echo "SSH_HOST ✅" || (echo "SSH_HOST ❌"; exit 1)
          [ -n "${{ secrets.SSH_USER }}" ] && echo "SSH_USER ✅" || (echo "SSH_USER ❌"; exit 1)
          [ -n "${{ secrets.SSH_PASSWORD }}" ] && echo "SSH_PASSWORD ✅" || (echo "SSH_PASSWORD ❌"; exit 1)
          [ -n "${{ secrets.TARGET_DIR }}" ] && echo "TARGET_DIR ✅" || (echo "TARGET_DIR ❌"; exit 1)
          test -d modules/addons/timekeeper && echo "Found modules/addons/timekeeper/ ✅" || (echo "Missing modules/addons/timekeeper/ ❌"; exit 1)
          ls -la modules/addons/timekeeper | sed -n '1,60p'

      # Remote BEFORE (timestamp + hash)
      - name: Remote state BEFORE
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE_DIR="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
            echo "REMOTE_DIR: $REMOTE_DIR"
            ls -la "$REMOTE_DIR" || echo "(remote dir missing)"
            ls -la "$REMOTE_DIR/timekeeper.php" || echo "(remote file missing)"
            if command -v md5sum >/dev/null; then md5sum "$REMOTE_DIR/timekeeper.php" || true; else shasum "$REMOTE_DIR/timekeeper.php" || true; fi

      # Ensure remote directory exists
      - name: Ensure remote directory exists
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE_DIR="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
            mkdir -p "$REMOTE_DIR"

      # Remove the file to guarantee overwrite
      - name: Remove remote file (force fresh copy)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE_DIR="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
            rm -f "$REMOTE_DIR/timekeeper.php" || true

      # Upload recursively from repo to server
      - name: Upload add-on via SFTP (recursive)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          source: "modules/addons/timekeeper/**"
          target: "${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
          overwrite: true
          debug: true

      # Remote AFTER (timestamp + hash)
      - name: Remote state AFTER
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE_DIR="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
            echo "REMOTE_DIR: $REMOTE_DIR"
            ls -la "$REMOTE_DIR/timekeeper.php" || echo "(remote file missing)"
            if command -v md5sum >/dev/null; then md5sum "$REMOTE_DIR/timekeeper.php" || true; else shasum "$REMOTE_DIR/timekeeper.php" || true; fi
