name: Deploy WHMCS Timekeeper (DEV)

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/addons/timekeeper/**'
      - '.github/workflows/deploy-whmcs-timekeeper.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-whmcs-timekeeper-dev
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sanity: secrets + local folder
      - name: Sanity check
        run: |
          set -e
          [ -n "${{ secrets.SSH_HOST }}" ] && echo "SSH_HOST ✅" || (echo "SSH_HOST ❌"; exit 1)
          [ -n "${{ secrets.SSH_USER }}" ] && echo "SSH_USER ✅" || (echo "SSH_USER ❌"; exit 1)
          [ -n "${{ secrets.SSH_PASSWORD }}" ] && echo "SSH_PASSWORD ✅" || (echo "SSH_PASSWORD ❌"; exit 1)
          [ -n "${{ secrets.TARGET_DIR }}" ] && echo "TARGET_DIR ✅" || (echo "TARGET_DIR ❌"; exit 1)
          test -d modules/addons/timekeeper && echo "Found modules/addons/timekeeper/ ✅" || (echo "Missing modules/addons/timekeeper/ ❌"; exit 1)
          ls -la modules/addons/timekeeper | sed -n '1,60p'

      # Remote BEFORE
      - name: Remote state BEFORE
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            DIR="${{ secrets.TARGET_DIR }}"
            echo "REMOTE DIR: $DIR"
            ls -la "$DIR" || echo "(remote dir missing)"
            if [ -f "$DIR/timekeeper.php" ]; then
              ls -la "$DIR/timekeeper.php"
              (command -v md5sum >/dev/null && md5sum "$DIR/timekeeper.php") || shasum "$DIR/timekeeper.php" || true
            else
              echo "(remote timekeeper.php missing)"
            fi
            # Warn if a nested copy exists from previous bad uploads
            if [ -f "$DIR/modules/addons/timekeeper/timekeeper.php" ]; then
              echo "⚠ Found nested copy at $DIR/modules/addons/timekeeper/timekeeper.php"
            fi

      # Upload recursively and strip leading path components (modules/addons/timekeeper → .)
      - name: Upload add-on via SFTP (recursive, strip path)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          source: "modules/addons/timekeeper/**"
          target: "${{ secrets.TARGET_DIR }}"
          overwrite: true
          strip_components: 3
          debug: true

      # Remote AFTER
      - name: Remote state AFTER
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            DIR="${{ secrets.TARGET_DIR }}"
            ls -la "$DIR/timekeeper.php" || echo "(remote file missing)"
            if [ -f "$DIR/timekeeper.php" ]; then
              (command -v md5sum >/dev/null && md5sum "$DIR/timekeeper.php") || shasum "$DIR/timekeeper.php" || true
            fi
            # Optional tidy-up: remove any accidental nested tree if it exists
            if [ -d "$DIR/modules/addons/timekeeper" ]; then
              echo "Cleaning nested $DIR/modules ..."
              rm -rf "$DIR/modules"
            fi
