name: Deploy WHMCS Timekeeper (DEV)
on:
  push:
    branches: [ main ]
    paths:
      - 'modules/addons/timekeeper/**'
      - '.github/workflows/deploy-whmcs-timekeeper.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Confirm the file exists in the repo (both possible layouts)
      - name: Check local paths
        run: |
          set -e
          echo "Looking for modules/addons/timekeeper/timekeeper.php ..."
          if [ -f modules/addons/timekeeper/timekeeper.php ]; then
            echo "FOUND: modules/addons/timekeeper/timekeeper.php"
            LOCAL_FILE="modules/addons/timekeeper/timekeeper.php"
          elif [ -f timekeeper/timekeeper.php ]; then
            echo "FOUND: timekeeper/timekeeper.php"
            LOCAL_FILE="timekeeper/timekeeper.php"
          else
            echo "❌ timekeeper.php not found in expected locations"
            echo "Repo tree:"
            find . -maxdepth 4 -type f -name 'timekeeper.php' || true
            exit 1
          fi
          echo "Using LOCAL_FILE=$LOCAL_FILE"
          ls -la "$LOCAL_FILE"

      # BEFORE upload: show remote file timestamp
    - name: Remote state before
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 2222
        script: |
          ls -la "${{ secrets.TARGET_DIR }}/modules/addons/timekeeper/timekeeper.php" || echo "(remote missing)"
          
      # Upload the WHOLE add-on recursively
      - name: Upload add-on via SFTP (recursive)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          source: "timekeeper/**"    # ← this matches your repo layout
          target: "${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
          overwrite: true
          debug: true

     # AFTER upload: show remote file timestamp
    - name: Remote state after
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 2222
        script: |
          ls -la "${{ secrets.TARGET_DIR }}/modules/addons/timekeeper/timekeeper.php" || echo "(remote missing)"
