name: Deploy WHMCS Timekeeper (DEV)
on:
  push:
    branches: [ main ]
    paths:
      - 'modules/addons/timekeeper/**'
      - '.github/workflows/deploy-whmcs-timekeeper.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Confirm the file exists in the repo (both possible layouts)
      - name: Check local paths
        run: |
          set -e
          echo "Looking for modules/addons/timekeeper/timekeeper.php ..."
          if [ -f modules/addons/timekeeper/timekeeper.php ]; then
            echo "FOUND: modules/addons/timekeeper/timekeeper.php"
            LOCAL_FILE="modules/addons/timekeeper/timekeeper.php"
          elif [ -f timekeeper/timekeeper.php ]; then
            echo "FOUND: timekeeper/timekeeper.php"
            LOCAL_FILE="timekeeper/timekeeper.php"
          else
            echo "❌ timekeeper.php not found in expected locations"
            echo "Repo tree:"
            find . -maxdepth 4 -type f -name 'timekeeper.php' || true
            exit 1
          fi
          echo "Using LOCAL_FILE=$LOCAL_FILE"
          ls -la "$LOCAL_FILE"

      # Show the remote file BEFORE upload (so we can compare)
      - name: Remote state before
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper/timekeeper.php"
            echo "Remote path: $REMOTE"
            ls -la "$REMOTE" || echo "(remote file missing)"

      # Upload the WHOLE add-on recursively
      - name: Upload add-on via SFTP (recursive)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          source: "modules/addons/timekeeper/**"
          target: "${{ secrets.TARGET_DIR }}/modules/addons/timekeeper"
          overwrite: true
          debug: true

      # Show the remote file AFTER upload
      - name: Remote state after
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            set -e
            REMOTE="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper/timekeeper.php"
            echo "Remote path: $REMOTE"
            ls -la "$REMOTE" || echo "(remote file missing)"

            set -e
            REMOTE="${{ secrets.TARGET_DIR }}/modules/addons/timekeeper/timekeeper.php"
            echo "Remote path: $REMOTE"
            ls -la "$REMOTE" || echo "(remote file missing)"
